name: Testing

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          # repo-token is necessary to avoid the rate limit issue
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "3.x"

      - name: Build
        run: make build

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Test
        run: make test
